prod-devel-rcar.yaml: Do not install Qemu into uInitramfs image
After switching to Kirkstone we face the following issue:
ERROR: core-image-thin-initramfs-1.0-r0 do_image_cpio:
The initramfs size 730231(K) exceeds INITRAMFS_MAXSIZE: 131072(K)

The have got a bloated initramfs and the significant part was caused
by Qemu. So exclude it (as it is not used so far) and increase
INITRAMFS_MAXSIZE by 64MB since there is still no free space:
ERROR: core-image-thin-initramfs-1.0-r0 do_image_cpio:
The initramfs size 144638(K) exceeds INITRAMFS_MAXSIZE: 131072(K)

TODO: Investigate what else increases the size and trim
in order to set previous limitation back if feasible.

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>